language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sudo dpkg-buildpackage --no-sign
after_success:
- sh travis/push.sh
env:
  global:
    secure: "fYugXTFzzoQktl4UDtFcXC7CQlI9jxNjvaou3ksbOv0Ce3TIPnZkiwdXoFlYD1ri4ILdWDZjKCuYEhmg244b9f0uqbC5gPivvcLBhmAwf6D7i1K/QCaLD8KFoqJbYIKS8NA7R5AWr1oW1TBpm7qBb79eddM8/6AurUnxjEW8ywQqwRuASeabP0cmvxsguGTscE0EboagXM31BTMVD8C2BPMFiHXmBpCFzM4tWa5Jcc7I93O7qFFoYJXRhgh2TgoNlJwKylPazBGp5cgYkbxJDjQhs6Uqw428NOU5dsSgH8JLTHEOGO4Jo3FVAMOacZMl8tIzsVA0T/RwI6TVjsP0AlU5jJoPpQtiYN1fNmzMzOSn0y2gyHwZKxEXGX61EcwPbVKmaFk2CbSzMAZxA8oQLVkSaMpcOmLeeTc5smOduKHE8VQ8p/J/O8/HXCYHytbXXxAOPlOIjZmpj/PQUbUkoO760wO1CCwSBTxreGO45jEoRAelJDD5e8H5LwcegpGu0UKKsYeefx9/XHDEpGPAsdgDylfGm80/Mj96aJk/12mRrS4+87V4T3lwItoGNBEMYwHwpCLf2GzS7ozP4gE2T4WNzV8NdeZknZlrBU4o3fjiPWC0s+TBeg0bYQD6N4CxDEwM3TY6LNwDik2/z3bjAH2Bi1ct7V7YcakJheJ442M="
