language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- echo $GH_TOKEN
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sudo dpkg-buildpackage --no-sign
after_success:
- sh travis/push.sh
env:
  global:
    secure: "kiM1835UiadV2bQdk2mz8eepED2eeWp9ljk8DO/TYrwen9u3Jyh+r+W5sejaAof77wAodiT0M7PDSuMbhswIjvuWyRrh44D8FOCzF2LjXnlihUikS2CSOPA6mstt2RT60d4EnPWh3rzJIbnazlxiMbPo5ErE34rjG7uIikwGrQjW9qTGWxURspPa/EB2Yov1W6ObP2c6Z1V8HdUZuNVqctOCT+aK4oGHS2d6jhbtK8WayfZsLsdhurWBz+7/EG02nVUM0pW1cf11FFBT1+pHNIjamuPaAH/0bibNkaDixR7AwLmFfjb/yiSFj2nQQ/7TlufcXPScVnLhzixBG5oiFuenbSG4MQcgaUN26rrIYKXTVdwq0gZ1pJj4/z6PcKN6z0q988A1z4IKIJEwbZx0y8RbtmTJsCaqmK2ZEe6TDmt4SfhSnQWAUt9n5wv9I+Mx7WuimbF8kzJBLT81fMQAzLG62P225r5oszBcGQkmW54ttbC6mknbm2ZJzjg5dlrgKq8KVZ3DnYMRra8VT3f5TpTCK0TClUqQ4eoJuuFO3JAaHHuJPV7nez4bjASVdrtT1DtYKhpcSSgBOE3fgehRryPaICoG005FpbQkWskxyhBgA8FtWXQUvCkWZV2o0EjcVcAI9fEa1nKZS5a+F1S7RhzXxniWFNDMsSNCqevsKTY="
