language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update -qq
- sudo apt-get install debhelper libblkid-dev libmount-dev libparted-dev qtbase5-dev
  qttools5-dev-tools
script:
- sudo dpkg-buildpackage --no-sign
after_success:
- sh travis/push.sh
env:
  global:
    secure: "QTy0h7tBBFSuwOrPvYkYa3NiVFT57jE4Nyr+wFYrUBe4ftd4K+YHd7m2OyWNFcVXbw7eh8H4WgcIufoisLpCsFTntP9jw01w10XBnjtvajC5EN/nGv+LHnabL7X5zVaZex0fokpxEsd6EiBFSPR0RcYrGZ7gto7y6wPigy3707jxgdsEqSiW8VUFMw1J6dX2AvkjBj0MRI1jYL/6rHDRV9AxdXaAdAxOoVkZ1sW6AKegU7df3jL0muQNY2Fr/Rj3vK+XdkZsHYOkQIvldsbiunLxcGUllCL/oQ4L5lYJuniOVg+6AwK4fBjFw0c10hlnkWtDJcjZI9AOsWEeN7iddPv025S8iYSno9sqZxOaGAH0CO1dAzP0tV0neM9N4RGBKKDZoE3evC1DF0OTmnKcOqiVtnGTyQZrUpjR+TeSQv6iAy1DHsJ76CCUIRvhY94zh8zpZnqaz08u5y8jktvKFVWIASaIImkfRSbE6T3nfmp8tdDjPyGyn9ejpJfblSKlKel9/ByR5u4QB+W7vkS3EdAxzqvzksHp2i+hDKxsxvK90quFUgkkob1d/6dEY1CN6HQmNBp505uj67WWLtgK8yQ358sNPKmFedNTAJTX2xeZkgab90v16fh+TYufXnH9l+MGyenmmDuw0xkzoSapa4BQ29Unj2jfpm80FJ3PIgs="
