language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install debhelper libblkid-dev libmount-dev libncursesw5-dev libparted-dev qtbase5-dev qttools5-dev-tools
script:
- qmake ./systemback.pro
- make
