language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
script:
- qmake ./systemback.pro
- make
