name: Build and Release Debian Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:24.04          
          buildpackage-opts: --build=binary --no-sign
          # When change deb package name as git rev id
          # before-build-hook: debchange --controlmaint --local="+ci${{ github.run_id }}~git$(git rev-parse --short HEAD)" "CI build"
          extra-build-deps: devscripts git equivs debhelper build-essential
          host-arch: amd64
          artifacts-dir: debian/artifacts

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: debian/artifacts/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: debian-package
          path: .

      - run: ls -R .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
